[package]
name = "neohertz/neonet"
description = "A simplified networking system for roblox game development. This system is not entirely "
version = "0.1.6"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]